Propogate changes to nginx-sm
meshery/meshery-nginx-sm pull request #151
Opened 2022-09-03 04:18 UTC by Rohith-Raju

**Description**

This PR fixes #
Propagation changes made from [this](https://github.com/meshery/meshery-traefik-mesh/pull/219/files)

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-09-03 04:48 UTC, MUzairS15 requested changes
@Rohith-Raju Try building locally first before committing, you will get all the error and you can make appropriate changes.

2022-09-03 04:48 UTC, MUzairS15 commented on nginx/nginx.go
> +}p
Remove this

2022-09-03 04:48 UTC, MUzairS15 commented on nginx/oam.go
> +				mesh.streamErr(ee.Summary, ee, err)
mesh?? mesh --> nginx

2022-09-03 04:48 UTC, MUzairS15 commented on nginx/oam.go
> +			mesh.streamErr(ee.Summary, ee, err)
here also same change, mesh --> nginx

2022-09-03 05:36 UTC, leecalcote commented
@Rohith-Raju If you haven’t built antacid these changes before submitting for others to spend their time reviewing… It would seem that you have, yet again, not done your homework but are asking others to do it for you.

Perhaps I’m misunderstanding the situation, but given the number of times that we have run into the situation I don’t believe that the benefit of the doubt is appropriate. Just like it’s not appropriate to knowingly turn in an incomplete assignment with the expectation that others carry it to completion.

2022-09-03 05:49 UTC, Rohith-Raju commented
@leecalcote truly sorry, won't happen again. Thought this was a plug-and-play kinda thing, but it is not. I should've known better.I'l l compile and make changes accordingly.

2022-09-03 05:58 UTC, leecalcote commented
I hear that and if there is any type of issue to learn on, this is a great type to do so with. My ask is that you be upfront with me maintainers, set appropriate expectations and both do your homework and document your studies as proof of diligence.

2022-09-03 10:43 UTC, Rohith-Raju commented
@leecalcote, Yes, I'll redo the entire changes

2022-09-04 05:29 UTC, gr455 commented
@Rohith-Raju there are only very small changes required after this PR, I can make them and keep your commits so you get the credit for your work. On to the next one for you :smile:

2022-09-04 07:26 UTC, Rohith-Raju commented
@gr455 sounds good, I'm more than happy to make changes if you point them out :smile:

2022-09-04 09:11 UTC, gr455 commented
> @gr455 sounds good, I'm more than happy to make changes if you point them out so that I'd know where I went wrong. smile

Oh, @MUzairS15 has pointed out the problems. Very small changes though, I did them. No problem. Thanks for doing the major part :smile:

2022-09-04 09:52 UTC, Revolyssup approved these changes

2022-09-04 09:53 UTC, merged