Make meshery logo consistent.
meshery/meshery-nginx-sm pull request #157
Opened 2022-09-28 11:58 UTC by NPDebs

**Description**
This PR fixes #156

![Screenshot_20220928-121402_Chrome](https://user-images.githubusercontent.com/105166953/192772096-37f32841-c710-4ce1-8315-94f749f0f971.jpg)

**Notes for Reviewers**
The meshery logo now looks legible in both light and dark mode. The same goes for the Slack logo.
Thank you.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-09-28 12:43 UTC, legendarykamal approved these changes
yo looks sleek ! thank you @NPDebs :+1:

2022-09-28 17:46 UTC, NPDebs commented
Thank you! 🙌🏼💃🏽

2022-10-03 16:04 UTC, Nikhil-Ladha reviewed
Please copy the images to this repo and use the relative path to the images in the README

2022-10-03 19:49 UTC, NPDebs commented
Sure. I'll get right on it! 🙌🏼

2022-10-03 20:38 UTC, NPDebs commented
@Nikhil-Ladha & @legendarykamal ...everything looks good on my end. Could you kindly review again? Thank you.

2022-10-04 02:46 UTC, legendarykamal requested changes

2022-10-04 02:46 UTC, legendarykamal commented on README.md
> +<a href="https://meshery.io/community">
Oops Wrong redirection, this should redirect to joining slack.

2022-10-04 02:46 UTC, legendarykamal commented on README.md
> +<a href="http://slack.layer5.io">
and this should actually redirect to https://meshery.io/community

2022-10-04 02:46 UTC, legendarykamal commented on README.md
> +  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/readme/slack-128.png" width="110px" align="right" style="margin-
This also comes from meshery repo, please add the logo in this repo only.

2022-10-04 05:05 UTC, NPDebs commented on README.md
> +<a href="https://meshery.io/community">
Shoot. 🙈 Thanks for spotting that out! 🙌🏼

2022-10-04 05:11 UTC, NPDebs commented on README.md
> +<a href="http://slack.layer5.io">
Done. Thank you. 🤝🏻

2022-10-04 05:15 UTC, NPDebs commented on README.md
> +  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/readme/slack-128.png" width="110px" align="right" style="margin-
All done. 🙂

2022-10-04 05:17 UTC, NPDebs commented
@legendarykamal I've made the necessary changes. Thanks for lending your keen eyes. 👀 👍🏻

2022-10-05 09:51 UTC, legendarykamal requested changes
All looks fine just one more change needed.

2022-10-05 09:51 UTC, legendarykamal commented on README.md
> +<source media="(prefers-color-scheme: light)" srcset="./img/readme/meshery-logo-tag-light-text-side.svg" width="70%" align="center" style="margin-bottom:20px;">
@leecalcote and we have agreed to get rid of that tagline present in the light mode. Please replace it , see meshery/meshery for ref on which one to use.

2022-10-05 10:22 UTC, NPDebs commented on README.md
> +<source media="(prefers-color-scheme: light)" srcset="./img/readme/meshery-logo-tag-light-text-side.svg" width="70%" align="center" style="margin-bottom:20px;">
True, true.
It seems off that one mode has the tagline when another doesn't. 🤔

I'll fix that right away! 🤝🏻

2022-10-05 10:41 UTC, NPDebs commented
All done @legendarykamal || @Nikhil-Ladha 👍🏻

2022-10-09 00:19 UTC, NPDebs commented
👀 Subtle reminder that this still exists. 🌝|| @legendarykamal @Nikhil-Ladha

2022-10-09 02:44 UTC, legendarykamal approved these changes
LGTM 🚀

2022-10-09 05:01 UTC, Nikhil-Ladha approved these changes
Lgtm

2022-10-09 05:01 UTC, merged

2022-10-09 05:03 UTC, legendarykamal commented
yeaaa @NPDebs 👏