externalize config
meshery/meshery-nginx-sm pull request #192
Opened 2023-01-30 20:28 UTC by ayushthe1

Signed-off-by: ayush_gitk <ayushsharmaa101@gmail.com>

**Description**
externalize config and camelcase the keys in `metadata.json`

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-01-30 20:32 UTC, ayushthe1 commented on build/config.go
> +	DefaultGenerationURL = "https://raw.githubusercontent.com/nginxinc/nginx-service-mesh/" + LatestVersion + ""
I have confusion on which file to reference for `DefaultGenerationURL`. Could anyone point it out.

2023-01-30 21:23 UTC, Revolyssup requested changes

2023-01-30 21:23 UTC, Revolyssup commented on build/meshmodel_metadata.json
> +	"svgColor":       "",
Why is the svgColor empty?

2023-01-30 21:23 UTC, Revolyssup commented on build/config.go
> +	DefaultGenerationURL = "https://raw.githubusercontent.com/nginxinc/nginx-service-mesh/" + LatestVersion + ""
Use `DefaultGenerationMethod` as  `adapter.HelmCHARTS` along with previous `DefaultGenerationURL`.
nginxinc/nginx can be used with utils.GetLatestTagSorted to get the latest version and when we have the latest version then the older way of generation and URL can be used.

2023-01-31 13:50 UTC, ayushthe1 commented
@Revolyssup made the changes as you pointed out but i can't figure out why the e2e tests are failing.

2023-02-07 20:36 UTC, Revolyssup approved these changes

2023-02-07 20:36 UTC, merged