change the `category` key across the whole adapter
meshery/meshery-nginx-sm pull request #210
Opened 2023-03-18 15:23 UTC by ayushthe1

**Description**

This PR changes `category" : "abc"`  to `"category" : {"name" : "abc" ,"metadata":null}`

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-04-04 21:47 UTC, leecalcote requested changes

2023-04-04 21:47 UTC, leecalcote commented on build/config.go
> +	Category: "Orchestration & Management",
Change to "Cloud Native Network", please.

2023-04-28 21:53 UTC, ayushthe1 commented
@leecalcote @Revolyssup Could you please merge this pr if it's good to go.

2023-04-29 05:31 UTC, leecalcote commented
The Category is correct. The Metadata looks a bit off, though.

2023-06-23 08:07 UTC, closed without merging