Issue#222 : Updated images and references for Meshery logo
meshery/meshery-nginx-sm pull request #232
Opened 2023-05-16 11:05 UTC by Ahmadshen

**Description**
This PR fixes #222 

This PR updates the images and references in the repository to use the Meshery logo instead of the Layer5 logo. It also adds conditional rendering based on the user's selected theme. The following changes have been made:

I replaced the previous logo with the Meshery-celebration-Light and Meshery-celebration-Dark images.
Updated the <picture> element in the .github/config.yml file to use the appropriate image sources for light and dark themes.
Modified the firstPRMergeComment section in the config.yml file to display the new image using the <picture> element.

**Notes for Reviewers**
Please review the changes made to update the images and references in the repository. Ensure the new images are correctly displayed based on the user's selected theme. Test the changes locally and verify that they are functioning as expected.

I have followed the contribution conventions as mentioned in the community guidelines:

I have included a descriptive title for this PR, starting with [<component-name>].
I built and tested the changes before submitting this PR.
I have signed my commits.
Thank you for reviewing my contribution. I would greatly appreciate your feedback and guidance.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-05-20 19:12 UTC, thisiskaransgit requested changes

2023-05-20 19:12 UTC, thisiskaransgit commented on .github/config.yml
> + </picture>
- We are using Raw github URLs for image targets
- Images should be sourced from the original repo, not your forked one

2023-05-20 19:12 UTC, thisiskaransgit commented on .github/config.yml
>    Thanks for your contribution to the Layer5 community! :tada:
```suggestion
  Thanks for your contribution to Meshery! :tada:
```

2023-05-20 19:47 UTC, Ahmadshen reviewed
Hi, I have updated the changes as required. Please have a look at it and let me know your feedback. 
ALso, thank you for your feedback and correction, this means a lot! :)

2023-05-20 19:48 UTC, Ahmadshen commented on .github/config.yml
> + </picture>
Thank you for your feedback, Karan. I have done changes as required. Please take a look and let me know. Thanks a lot

2023-05-21 16:09 UTC, thisiskaransgit commented on .github/config.yml
> + </picture>
@Ahmadshen, the URLs should be pointing at the master branch not a specific commit, if you are stuck take help from the similar PRs opened throughout the project

2023-05-21 16:55 UTC, Ahmadshen reviewed
Please have a look. Hopefully, this time, I am correct, and thank you for your feedback! : )

2023-05-21 17:09 UTC, Ahmadshen commented on .github/config.yml
> + </picture>
@thisiskaransgit  Thank you so much for your constant feedback and suggestions, this means a lot to me. I have done changes as required and hopefully this time, it's good!

2023-05-22 18:19 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-06-21 05:18 UTC, anshgoyalevil requested changes

2023-06-21 05:18 UTC, anshgoyalevil commented on .github/config.yml
> +  <img alt="Shows a black logo in light color mode and a white one in dark color mode.">
Please add a ```src="https://raw.githubusercontent.com/meshery/meshery-nginx-sm/master/.github/welcome/Meshery-celebration-Dark.svg"``` attribute here. This helps in adding a fallback image for browsers that do not support conditional rendering.

2023-06-21 05:18 UTC, anshgoyalevil commented on .github/config.yml
> +  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery-nginx-sm/master/.github/welcome/Meshery-celebration-Light.svg">
Interchange the dark and light with appropriate srcsets. The image with white text should be on a dark scheme, and vice versa.

2023-06-21 05:19 UTC, anshgoyalevil commented on .github/config.yml
> +  <img alt="Shows a black logo in light color mode and a white one in dark color mode.">
This change needs to be done in the ```<img>``` tag here.

2023-07-09 16:44 UTC, leecalcote approved these changes
Thanks!

2023-07-09 16:44 UTC, merged