Chore/error migration
meshery/meshery-nginx-sm pull request #27
Opened 2021-07-31 12:12 UTC by sayantan1413

**Description**

This PR:

migrates the current errors to be Error Utility Tool compatible .
- Updated the Release URL
- Updated the SMI test handler
- Update the github workflow

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-07-31 12:56 UTC, sayantan1413 commented
Hey @mgfeller please have a look at the [lint fix](https://github.com/meshery/meshery-nginx-sm/pull/27/commits/07b91ae8ebb4bc8a3c4973be58ebdb698228efb9) and [lint fix 2](https://github.com/meshery/meshery-nginx-sm/pull/27/commits/acc391efb4a88a877d060c74ab8a117cd9e5f37f). I made this changes to pass the checks. So will you please reverify once if these changes are going to breakdown any behaviour or the adapter. I have taken reference from here
- [lint fix](https://github.com/meshery/meshery-nginx-sm/pull/27/commits/07b91ae8ebb4bc8a3c4973be58ebdb698228efb9) -> https://stackoverflow.com/questions/40429072/golang-file-transfer-stops-without-any-error/40429443#40429443
- [lint fix 2](https://github.com/meshery/meshery-nginx-sm/pull/27/commits/acc391efb4a88a877d060c74ab8a117cd9e5f37f) -> https://github.com/pulumi/pulumi/pull/3446/commits/3c2b2d62fbb024116af030d6f550a1dc05a3583b

2021-08-05 03:32 UTC, leecalcote commented
@Shreyas220 will you have a peek here?

2021-08-06 06:13 UTC, Shreyas220 approved these changes
looks good to me :smile:

2021-08-07 21:23 UTC, DelusionalOptimist requested changes

2021-08-07 21:23 UTC, DelusionalOptimist commented on internal/config/config.go
> +		return nil, fmt.Errorf("bad status: %s", resp.Status)
I believe this can be made a meshkit error as well?

2021-08-07 21:23 UTC, DelusionalOptimist commented on internal/config/config.go
> +		_, err = io.CopyN(out, r, 1024)
@sayantan1413 @Shreyas220 do we have a solution other than this? This here would not copy all the bytes of the downloaded binary thus resulting into a useless one.

2021-08-13 19:06 UTC, sayantan1413 commented on internal/config/config.go
> +		_, err = io.CopyN(out, r, 1024)
Hey @DelusionalOptimist I searched a lot but could not found any. So should I revert the change here ?

2021-08-13 19:14 UTC, DelusionalOptimist commented on internal/config/config.go
> +		_, err = io.CopyN(out, r, 1024)
no worries @sayantan1413. Feel free to revert this to how it was eariler and put a nosec here as well.
We'll take a look into this once this adapter gets bit of a revival. ( and then we'll move away from this CLI based way anyway ).

2021-08-13 19:16 UTC, sayantan1413 commented on internal/config/config.go
> +		_, err = io.CopyN(out, r, 1024)
Sure @DelusionalOptimist

2021-08-14 17:36 UTC, sayantan1413 commented
Hey @DelusionalOptimist the lint check fail if I change it to `copy` and also providing the nosec also.

2021-08-14 19:07 UTC, DelusionalOptimist commented on internal/config/config.go
> +		// #nosec G204
```suggestion
		// Temporary. We'll get rid of this later. 
		// #nosec
```

2021-08-14 20:05 UTC, DelusionalOptimist approved these changes
Thanks @sayantan1413 :heavy_check_mark:

2021-08-14 20:05 UTC, merged