added Runtime Generation and Registration of Components
meshery/meshery-nginx-sm pull request #42
Opened 2021-09-28 00:34 UTC by Shreyas220

**Description**
added Runtime Generation and Registration of Components

This PR fixes #41 
![image](https://user-images.githubusercontent.com/55346934/135003385-ae9c1d26-9a31-4cbf-bd40-93b36e9590b8.png)

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-09-28 02:25 UTC, leecalcote commented on main.go
> +	return "http://localhost:9081"
@utkarsh-pro I see this hardcoding in other adapters as well. Do we have sufficient justification for this hardcoding and that of line 126 as well?

2021-09-28 02:28 UTC, leecalcote commented on main.go
>  	log.Info("Adaptor Listening at port: ", service.Port)
```suggestion
	log.Info("Adapter Listening at port: ", service.Port)
```

2021-09-28 07:34 UTC, Revolyssup reviewed
@Shreyas220  Latest workload components are not being registered.
URL that has been passed does not download manifests.
If generation method is manifests, you have to pass a link to download manifests(refer istio)
If helm then you have to pass the link to download help repo which has to have a "crd" directory.

2021-09-28 08:01 UTC, Revolyssup commented
@Shreyas220  Instead use something like this https://github.com/nginxinc/helm-charts/blob/master/stable/nginx-ingress-0.10.0.tgz?raw=true , and replace 0.10.0 with latest version using something like getLatestValidAppVersionAndChartVersion( refer to OSM adapter)

2021-09-29 03:54 UTC, leecalcote commented on main.go
> +	return "http://localhost:9081"
@utkarsh-pro

2021-09-29 03:55 UTC, leecalcote commented
Thanks for this review, @Revolyssup

2021-09-29 10:28 UTC, utkarsh-pro commented on main.go
> +	return "http://localhost:9081"
It is not exactly hardcoding actually. It is a fallback. Adapters first check in there environment variables to find their location (or meshery's location) and in case they don't find it, they will fallback to these hardcoded values. There has to be a fallback right?

**Lee: In what case they won't have the environment variable?**
Me: Mostly during development.
**Lee: Developers can add it during development in there environment, or maybe add this in the makefile recipe?**
Me: Yes, developers can add it and we can add it in the makefile recipe too, however I think that having a fallback is still better than ending up in a adapter state where these could potentially be empty strings.
**Lee: Then add checks in the adapter to ensure these are always provided to the adapter**
Me: Well yes, we can add the checks in the adapter. But what happens if the check fails? The adapter should not boot up? Maybe we can stop adapter startup if the check fails when we only have "patternops", considering that at the moment the meshery UI is driven by the "meshops", won't it be undesirable to not bootup?

2021-09-29 12:11 UTC, Revolyssup commented
@Shreyas220 
https://github.com/nginxinc/helm-charts/blob/master/stable/nginx-service-mesh-0.2.0.tgz?raw=true , this should be the url
and generation method should be HELM_CHART.
Have tested it, it works. Just one thing. instead of 0.2.0 , you will have to write a function to get the latest version.

2021-09-29 12:26 UTC, Shreyas220 commented
> @Shreyas220 https://github.com/nginxinc/helm-charts/blob/master/stable/nginx-service-mesh-0.2.0.tgz?raw=true , this should be the url and generation method should be HELM_CHART. Have tested it, it works. Just one thing. instead of 0.2.0 , you will have to write a function to get the latest version.
> 
> You can get traverse files here https://github.com/nginxinc/helm-charts, and can write some logic to extract nginx-service-mesh-.tgz from here

got it, thank you

2021-09-29 22:42 UTC, Revolyssup commented
@Shreyas220  heads up, upgrade to latest meshkit version and then therre will be two errors , change that string to array of string,

2021-10-01 10:39 UTC, Shreyas220 commented
@Revolyssup made a temp fix to get the latest workloads 
I am not able to get the names from this https://api.github.com/repos/nginxinc/helm-charts/contents/stable?ref=master

2021-10-02 11:40 UTC, Revolyssup requested changes

2021-10-02 11:40 UTC, Revolyssup commented on main.go
> +	go registerCapabilities(service.Port, log)        //Registering static capabilities
There are no static definitions or schemas currently. So this ofcourse results in an error that /templates/oam/workloads no such directory, because there is not. 
So either you can  create those definitions and schemas and push it there, Or as this PR is for runtime generation, you can comment this out for now. And add those static components in future.

2021-10-02 11:40 UTC, Revolyssup commented on nginx/error.go
> +func ErrRegisteringWorkload(err error) error {
You can remove these as well, as you are not using these errors anyways here.

2021-10-02 11:54 UTC, Shreyas220 commented on main.go
> +	go registerCapabilities(service.Port, log)        //Registering static capabilities
someone is parallelly working on creating a CI workflow for this [here](https://github.com/meshery/meshery-nginx-sm/issues/40) 
so I don't think it'll be long before we have them

2021-10-02 11:56 UTC, Revolyssup commented on main.go
> +	go registerCapabilities(service.Port, log)        //Registering static capabilities
okay then leave it like this

2021-10-02 11:57 UTC, Shreyas220 commented on main.go
> +	go registerCapabilities(service.Port, log)        //Registering static capabilities
resolving this

2021-10-02 13:37 UTC, Revolyssup commented
LGTM

2021-10-02 13:37 UTC, Revolyssup approved these changes

2021-10-06 21:09 UTC, leecalcote commented on main.go
> +	return "http://localhost:9081"
You pulled a "Lee" on me... and I like it. 😄

2021-10-06 22:17 UTC, DelusionalOptimist commented on main.go
> +	str, err := config.ChangeReleaseString()
@Shreyas220 I don't exactly know why we have this so do correct me if I'm wrong.
I guess this is here just for converting the service mesh's version (`AppVersion`) to its helm chart version (`Version`) so the tar containing the crds can be obtained, right? In that case, we have functions for doing so already which fetch these from helm repo index and save us from reimplementing. These 2 should be helpful https://github.com/layer5io/meshkit/blob/f0e5782dceba6f0bdebb654cbc9e63f7d767d8c4/utils/kubernetes/apply-helm-chart.go#L426-L432

2021-10-07 03:35 UTC, Shreyas220 commented on main.go
> +	str, err := config.ChangeReleaseString()
Yeah I did try using that but it was returning an empty string, so made a temp fix

2021-10-07 05:00 UTC, Shreyas220 commented on main.go
> +	str, err := config.ChangeReleaseString()
or should we get it from [here](https://github.com/nginxinc/nginx-service-mesh/blob/main/helm-chart/Chart.yaml )

2021-10-08 03:07 UTC, Shreyas220 commented on main.go
> +	str, err := config.ChangeReleaseString()
thanks @DelusionalOptimist

2021-10-08 23:49 UTC, DelusionalOptimist approved these changes
LGTM. :+1:

2021-10-09 11:16 UTC, merged