[CI] add pattern components generator workflow
meshery/meshery-nginx-sm pull request #50
Opened 2021-10-02 14:20 UTC by iamsdas

**Description**

This PR fixes #40 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-10-02 16:23 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +    needs: [check_nsm_version]
Should all the nsm be replaced with nginx here? These two are seperate adaptor I guess.

2021-10-02 16:26 UTC, iamsdas commented on .github/workflows/update-oam-defs.yml
> +    needs: [check_nsm_version]
I originally kept it as nginx-sm...then noticed the issue said "nsm adaptor"...then I replaced all the "nginx-sm" with "nsm" instead🤦

2021-10-02 16:27 UTC, iamsdas commented on .github/workflows/update-oam-defs.yml
> +    needs: [check_nsm_version]
So before I do anything else, can someone confirm what name I should use?

2021-10-02 17:21 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +    needs: [check_nsm_version]
@DelusionalOptimist "nginx" would be fine right ?

2021-10-02 17:24 UTC, warunicorn19 commented on .github/workflows/update-oam-defs.yml
> +    needs: [check_nsm_version]
I think nginx would make more sense, since we already use `nsm` for the NSM adapter

2021-10-02 17:37 UTC, iamsdas commented on .github/workflows/update-oam-defs.yml
> +    needs: [check_nsm_version]
`nginx` or `nginx-sm`?

2021-10-05 21:12 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +    needs: [check_nsm_version]
Let's go with `nginx-sm` :+1:

2021-10-06 14:46 UTC, Shreyas220 commented
@iamsdas can you provide the link where the workloads are being generated

2021-10-06 15:03 UTC, iamsdas commented
@Shreyas220 you can find them [here](https://github.com/meshery/meshery-nginx-sm/pull/50/commits/761f44afcc114c7de792cac40efde645010b1288)

2021-10-07 10:29 UTC, DelusionalOptimist requested changes

2021-10-07 10:29 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +          smpMeshName=NGINXSM
```suggestion
          smpMeshName=NGINX_SERVICE_MESH
```
SMP mesh name : )
https://github.com/service-mesh-performance/service-mesh-performance/blob/f5ffabafb5b4eed338123c4b10bb7942518f195a/spec/service_mesh.pb.go#L59

2021-10-07 10:29 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +          template='{"apiVersion":"core.oam.dev/v1alpha1","kind":"WorkloadDefinition","metadata":{},"spec":{"definitionRef":{},"metadata":{"@type":"pattern.meshery.io/mesh/workload","meshVersion":"'$
Missing meshVersion in generated workload definitions https://github.com/iamsdas/meshery-nginx-sm/commit/66757127548a2e7fc767ec3537831ee67a77e54d#diff-52c83c5775abd33ca3fbafc4abd55b6c5c2c1d41556d72983324f61805ba9940

2021-10-08 22:48 UTC, DelusionalOptimist requested changes

2021-10-08 22:48 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +            ."metadata"."name" = "'$(printf %s.nginxsm $nameUpper)'"
```suggestion
            ."metadata"."name" = "'$(printf %s.nginx-sm $nameUpper)'"
```

2021-10-08 22:48 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +            | ."spec"."definitionRef"."name"="'$definitionRef'"' > $dirPath/$nameLower.nginxsm_definition.json
```suggestion
            | ."spec"."definitionRef"."name"="'$definitionRef'"' > $dirPath/$nameLower.nginx-sm_definition.json
```

2021-10-08 22:48 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +            jq '.[]' > $dirPath/$nameLower.nginxsm.meshery.layer5io.schema.json
```suggestion
            jq '.[]' > $dirPath/$nameLower.nginx-sm.meshery.layer5io.schema.json
```

2021-10-08 22:48 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +          meshName=nginxsm
```suggestion
          meshName=nginx-sm
```

2021-10-08 22:48 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +          dirPath=../templates/oam/workloads/workloads-$NEW_NGINXSM_VERSION
```suggestion
          dirPath=../templates/oam/workloads/$NEW_NGINXSM_VERSION
```

2021-10-08 22:48 UTC, DelusionalOptimist commented on .github/workflows/update-oam-defs.yml
> +            definitionRef=$(printf %s.nginxsm.meshery.layer5.io $nameLower)
```suggestion
            definitionRef=$(printf %s.nginx-sm.meshery.layer5.io $nameLower)
```

2021-10-08 22:52 UTC, DelusionalOptimist approved these changes
Looks awesome :rocket:
Thanks @iamsdas : )

2021-10-08 22:52 UTC, merged