add operation for enabling automatic sidecar injection
meshery/meshery-nginx-sm pull request #60
Opened 2021-11-11 16:49 UTC by Shreyas220

Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>

**Description**
- added operation to prepare targeted namespace and enable nginx-sm automatic sidecar injection on it
- fixes an instance of misused meshkit logger

This PR fixes #33

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-11-12 11:35 UTC, utkarsh-pro approved these changes
LGTM

2021-11-12 12:26 UTC, leecalcote commented
@Shreyas220 will you have a look at the merge conflict?

2021-11-12 12:27 UTC, leecalcote requested changes

2021-11-12 12:27 UTC, leecalcote commented on nginx/error.go
> +	return errors.New(ErrLoadNamespaceCode, errors.Alert, []string{"Error occured while applying namespace "}, []string{err.Error()}, []string{}, []string{})
Please include probable cause and suggested remediation on all errors.

2021-11-17 13:00 UTC, leecalcote commented on nginx/error.go
> +	return errors.New(ErrLoadNamespaceCode, errors.Alert, []string{"Error occured while applying namespace "}, []string{err.Error()}, []string{"Trying to access a namespace which is not available"}, []s
@Shreyas220 Suggested remediation needed. Could be: "Verify presence of namespace. Confirm Meshery ServiceAccount permissions."

2021-12-05 15:58 UTC, leecalcote commented
@Revolyssup what do you think?

2021-12-05 16:14 UTC, Revolyssup commented
> @Revolyssup what do you think?

gtg

2021-12-06 11:29 UTC, utkarsh-pro approved these changes
LGTM

2021-12-06 11:30 UTC, merged